modLoader = "javafml"
loaderVersion = "[${forge_min_version},)"
issueTrackerURL = "https://github.com/${github_user}/${github_repo}/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_min_version},)"
ordering = "NONE"
side = "BOTH"
